config-version: 2

name: 'github_source'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.19.0"]

models:
    github:
        materialized: table
        intermediate:
            materialized: ephemeral
    github_source:
        materialized: ephemeral

