config-version: 2

name: 'github'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.19.0"]

models:
    github:
        materialized: table
        intermediate:
            materialized: ephemeral

vars:
    dbt_utils_dispatch_list:
        - fivetran_utils